### ISSUE TITLE
ODI: Possible to add more memory (RAM) on Q compute nodes (q13-16)

### ISSUE THREAD

**Issue by agopu** [IUSCA/sca-issues#2]
Mike reports that he is having to throttle QR-based processes to use fewer than available cores on q13-16 so the processes don't run out of RAM. We would like to explore the possibility of adding more memory (RAM) on those nodes. Granted, ODI already has the benefit of our providing dedicated compute nodes but I am thinking we may be able to swap out RAM chips from unused Q nodes (until we run into needing those nodes).

**Comment by agopu** [comment]
Will discuss this with @rperigo later today.

**Comment by agopu** [comment]
Ray & I stopped by the data center yesterday and bumped the RAM on q14 from 32 to 64GB, @youngmd to report back on how useful this is for the Illum. Correction process' efficiency (as well as overall improvements to QR and SWarp process execution times). We will adjust the other nodes as useful based on the feedback.

**Comment by agopu** [comment]
While the improvements were marginal in our tests last month, we figured more RAM would enable firing up an additional ODI worker node process as/when necessary so we decided to go ahead with upgrading all 4 ODI compute nodes.

After being backburnered for a while, @informaticianme & I knocked this out today when we were already at the data center for another reason.

**Comment by informaticianme** [comment]
Just for the purposes of tracking (and so I can look things up in the future if needed), I'll be adding a little detail to this issue here.

Arvind and I added RAM to the following servers:
* `numan.sca.iu.edu`
* `reznor.sca.iu.edu`
* `q13.sca.iu.edu`
* `q15.sca.iu.edu`
* `q16.sca.iu.edu`

New RAM was allocated to `numan` and `reznor`. Old RAM from qnodes at the top of the rack was removed from those blades and added to blades q13, q15, and q16 until each were maxed out.

Process wise, we performed the following steps:
* Logged into each virtual machine, shutdown the server (reznor had no VMs).
* Used `virsh list --all` on `numan` to check VM status.
* Logged into each physical host, shutdown the server.
* Unplugged KVM serial port, usb port, network cable, and power cables.
* Removed server, added RAM (did not consult manual for particular ram slots to use but all seems fine).
* Replace server in rack, replugin serial, usb, network, and power cables (use cord curl and ensure amperage load is distributed or at least close).
* Similar process for qnodes.

**Comment by informaticianme** [comment]
Relates to

**Comment by informaticianme** [comment]
Relates to https://github.com/IUSCA/int-issues/issues/49.
