### ISSUE TITLE
Vanity path

### ISSUE THREAD

**Issue by StephanieD123** [IUSCA/sca-issues#37]
For the "Whistle" app that we currently have here: https://rstudio.sca.iu.edu/connect/#/apps/17/access, can we have the link say Whistle instead of ...apps/17/access...?

Also, can we use our website domain biostats.indiana.edu/Shiny/Whistle? I forget if we talked about that - and what you would need from our IT web team?

Stephanie

**Comment by agopu** [comment]
Hi Stephanie,

I've added the 'vanity' URL - you can now access it at https://rstudio.sca.iu.edu/whistle

To your 2nd question, I don't think we discussed it previously. At the simplest, your IT admin (whoever operates that website) could setup a redirect on the biostats.indiana.edu webserver so that specific URL biostats.indiana.edu/shiny/whistle redirects to https://rstudio.sca.iu.edu/whistle. Would that work for you?

Best Regards,
-a

**Comment by StephanieD123** [comment]
Great – thanks. And if we re-publish a revised app with the name “Whistle” will it overwrite it, so the ‘vanity’ URL still holds for the updated version?

 

Sure, the pointer is a good idea.

 

Thanks,
Stephanie

**Comment by rperigo** [comment]
Hi Stephanie,

As I understand it, if you either A) re-publish from the same project folder or B) publish from a new Shiny app with the **exact same name**, it should work. In the former case, it will just update since it has already published to the server. In the latter, it should ask to overwrite.
